version: '3.8'

services:
  mariadb:
    image: mariadb:10.7
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sapassword
      MYSQL_DATABASE: candyshop
    ports:
      - "3306:3306"
    networks:
      - backend

  candyshop:
    build: .
    container_name: candyshop
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/candyshop
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: sapassword
    depends_on:
      - mariadb
    networks:
      - backend

networks:
  backend:
    driver: bridge
